# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20171031_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='supervisors',
        ),
        migrations.RemoveField(
            model_name='activityimage',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='supervisor',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityImage',
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.DeleteModel(
            name='Supervision',
        ),
    ]
