# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
