# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171031_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emergencyPhone',
            field=models.CharField(default=b'-', max_length=50),
        ),
    ]
