# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20171104_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emergencyPhone',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
